name: Nx CI → Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: '20'        # SWA uses Node 20 today

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write        # not used by SWA but future-proof
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci          # faster, locked versions
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=lint,test,export --parallel=3

      - name: Deploy to SWA
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "dist/apps/web/out"       # <- the exported folder
